### ISSUE TITLE
Doesn't work w/o node installed

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-rs#16]
Should automatically download and install latest parity/geth node for current OS into a private directory (under emerald), then run it.

List of nodes to download can be provided as a config file, like:
```
version: 1 #config format version
nodes:
  - type: geth
    version: 3.3.0
    binaries:
      - os: win
        url: https://site/geth-classic-win-3.3.0.zip # bittorrent and ipfs later
        signature:
          - type: sha256
            value: "28ecb202183e49f2092e675b699f5805c7d968c6c23c480f10f0d4cb20167c34"
      - os: darwin
        url: https://site/geth-classic-darwin-3.3.0.zip
        signature:
          - type: sha256
            value: "a8f833d03b5c0c1a198ebabf65645031746c2917e8dc3782f6211001fc0f1720"
```

for now just check hash of zip file, later we'll need to add validation against pgp signature
